<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="1" name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="1" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="SeleniumPractice.tests.ErrorValidationsTest">
        <methods>
          <include name="LoginErrorValidations"/>
          <include name="ProductErrorValidation"/>
          <include name="launchapplication"/>
          <include name="teardown"/>
        </methods>
      </class> <!-- SeleniumPractice.tests.ErrorValidationsTest -->
      <class name="cucumber.TestNGTestRunner">
        <methods>
          <include name="setUpClass"/>
          <include name="runScenario" invocation-numbers="0"/>
          <include name="tearDownClass"/>
        </methods>
      </class> <!-- cucumber.TestNGTestRunner -->
      <class name="SeleniumPractice.tests.SubmitOrderTest">
        <methods>
          <include name="launchapplication"/>
          <include name="teardown"/>
          <include name="SubmitOrder"/>
          <include name="OrderHistoryTest"/>
        </methods>
      </class> <!-- SeleniumPractice.tests.SubmitOrderTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
